TYPE_CHOICES = [
    'Apartment',
    'House',
    'Bed and breakfast',
    'Boutique hotel',
    'Bungalow',
    'Cabin',
    'Chalet',
    'Condominium',
    'Cottage',
    'Guest suite',
    'Guesthouse',
    'Hostel',
    'Hotel',
    'Kezhan',
    'Loft',
    'Resort',
    'Serviced apartment',
    'Townhouse',
    'Villa',
]
AMENITIES_CHOICES = [
    'Wifi',
    'Kitchen',
    'Washer',
    'Air conditioning',
    'Iron',
    'Free parking',
    'Dryer',
    'Heating',
    'Dedicated workspace',
    'TV',
    'Hair dryer',
    'Pool',
    'Hot tub',
    'EV charger',
    'Crib',
    'Gym',
    'BBQ grill',
    'Breakfast',
    'Indoor fireplace',
    'Smoking allowed',
    'Beachfront',
    'Waterfront',
    'Ski-in/ski-out',
    'Smoke alarm',
    'Carbon monoxide alarm',
]
