-- Drops all project tables.

USE mybnb;

DROP TABLE IF EXISTS Bookings;
DROP TABLE IF EXISTS Availability;
DROP TABLE IF EXISTS ListingComments;
DROP TABLE IF EXISTS UserComments;
DROP TABLE IF EXISTS BookingSlots;
DROP TABLE IF EXISTS Listings;
DROP TABLE IF EXISTS Hosts;
DROP TABLE IF EXISTS Renters;
DROP TABLE IF EXISTS Users;
